# Generated by Django 5.0.9 on 2024-10-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='availability',
            field=models.JSONField(default=dict),
        ),
    ]
