# Generated by Django 5.0.9 on 2024-10-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tutor_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='subjects',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
